//! Byte-anatomy diagram source (DOT) for the ziplist hash golden block.
//!
//! Rebuilds the `tests/golden.rs::hash_golden_bytes` fixture through the
//! crate's own ops, then derives every drawn element by decoding the bytes
//! with the crate's own primitives (`BlockHeader::parse`, `Cursor`,
//! `decode`) — the figure cannot disagree with the codec without this
//! program aborting.
//!
//! The committed artifact is the DOT source; the SVG is a render of it.
//! Regenerate both:
//!   cargo run -p ziplist --example block_anatomy \
//!     > docs/diagrams/ziplist-block-anatomy.dot
//!   dot -Tsvg docs/diagrams/ziplist-block-anatomy.dot \
//!     > docs/diagrams/ziplist-block-anatomy.svg
//!
//! A future CI freshness check diffs the regenerated DOT against the
//! committed one — the DOT is generator-owned text, stable across
//! graphviz versions, unlike rendered SVG bytes.

use std::fmt::Write as _;
use ziplist::{decode, encode_into, encoded_len, BlockHeader, Cursor, EntryVal, HashMut, Type};

const HDR_FILL: &str = "#B3CDE3"; // header fields
const TAG_FILL: &str = "#FBB4AE"; // entry tag byte
const DATA_FILL: &str = "#CCEBC5"; // entry data bytes
const BL_FILL: &str = "#F6E3B4"; // backlen byte
const INK: &str = "#22303C";
const BG: &str = "#FCFCFA";

/// tag + data length of an entry, from the public tier spec; verified in
/// `main` against `encoded_len` and a byte-identical re-encode.
fn tag_plus_data(val: &EntryVal) -> usize {
    match val {
        EntryVal::Uint(v) => match v {
            0..=250 => 1,
            251..=65535 => 3,
            65536..=16_777_215 => 4,
            16_777_216..=72_057_594_037_927_935 => 8,
            _ => 9,
        },
        EntryVal::Str(s) => {
            let mut varint = 1;
            let mut rest = s.len() >> 7;
            while rest > 0 {
                varint += 1;
                rest >>= 7;
            }
            1 + varint + s.len()
        }
    }
}

struct Span {
    start: usize,
    data_end: usize, // end of tag+data; backlen bytes run through `end`
    end: usize,
    desc: String,
}

fn main() {
    // The golden fixture, produced by the real ops.
    let mut buf = vec![0u8; 256];
    let mut h = HashMut::init(&mut buf).expect("init");
    h.hset(b"5", b"9").expect("hset 5");
    h.hset(b"z", b"ab").expect("hset z");
    let bytes: Vec<u8> = h.bytes().to_vec();

    // Derive spans with the crate's own decoder; abort on any mismatch.
    let hdr = BlockHeader::parse(&bytes).expect("header");
    assert_eq!(hdr.type_, Type::Hash, "fixture type drifted");
    let mut spans: Vec<Span> = Vec::new();
    let mut cur = Cursor::first(&bytes, &hdr);
    while let Some(c) = cur {
        let (val, total) = decode(&bytes, c.off).expect("entry decodes");
        let tpd = tag_plus_data(&val);
        assert_eq!(total, encoded_len(&val), "tier table drifted from codec");
        let backlen = total.checked_sub(tpd).expect("backlen underflow");
        assert!((1..=5).contains(&backlen), "backlen bytes out of range");
        // Re-encode and byte-compare: the drawn span is exactly the codec's.
        let mut re = vec![0u8; total];
        assert_eq!(encode_into(&val, &mut re), total);
        assert_eq!(re, bytes[c.off..c.off + total], "re-encode mismatch");
        let desc = match &val {
            EntryVal::Uint(v) => format!("Uint({v})"),
            EntryVal::Str(s) => format!("Str(\"{}\")", String::from_utf8_lossy(s)),
        };
        spans.push(Span {
            start: c.off,
            data_end: c.off + tpd,
            end: c.off + total,
            desc,
        });
        cur = c.next(&bytes);
    }
    assert_eq!(spans.len(), hdr.nentry as usize, "nentry != walked entries");
    assert_eq!(
        spans.last().expect("nonempty").start,
        hdr.tail_off as usize,
        "tail_off mismatch"
    );
    assert_eq!(
        spans.last().expect("nonempty").end,
        bytes.len(),
        "trailing bytes"
    );

    print!("{}", emit_dot(&bytes, &hdr, &spans));
}

fn emit_dot(bytes: &[u8], hdr: &BlockHeader, spans: &[Span]) -> String {
    // A byte grid is rigid: position IS the offset. Free-layout nodes and
    // clusters let graphviz stretch and pad, so the grid is emitted as one
    // HTML-like table label — contiguous cells, colspan rows for the
    // field/entry groupings, no layout freedom to fight.
    let n = bytes.len();
    let esc = |t: &str| {
        t.replace('&', "&amp;")
            .replace('<', "&lt;")
            .replace('>', "&gt;")
    };

    // fills per byte
    let mut fills = vec![HDR_FILL; n];
    for sp in spans {
        fills[sp.start] = TAG_FILL;
        for f in fills.iter_mut().take(sp.data_end).skip(sp.start + 1) {
            *f = DATA_FILL;
        }
        for f in fills.iter_mut().take(sp.end).skip(sp.data_end) {
            *f = BL_FILL;
        }
    }

    let mut s = String::new();
    let _ = writeln!(
        s,
        "// GENERATED by `cargo run -p ziplist --example block_anatomy` — do not edit."
    );
    let _ = writeln!(
        s,
        "// Derived from tests/golden.rs::hash_golden_bytes via the crate's own decoder."
    );
    let _ = writeln!(s, "digraph ziplist_block_anatomy {{");
    let _ = writeln!(
        s,
        "  graph [bgcolor=\"{BG}\", fontname=\"Helvetica\", fontsize=12, fontcolor=\"{INK}\", \
         label=\"ziplist hash block, {n} bytes ({ne} entries) — cells are bytes in offset order; \
tail_off marks the last entry's first byte\", labelloc=b];",
        ne = hdr.nentry
    );
    let _ = writeln!(s, "  node [shape=plaintext, fontcolor=\"{INK}\"];");
    let _ = writeln!(s, "  grid [label=<");
    let _ = writeln!(
        s,
        "    <TABLE BORDER=\"0\" CELLBORDER=\"1\" CELLSPACING=\"0\" CELLPADDING=\"5\" COLOR=\"{INK}\">"
    );

    // row 1: header-field group labels over their byte columns (kept
    // short so no label widens its byte column and breaks the even grid)
    let hdr_fields: [(usize, String); 5] = [
        (1, "type".into()),
        (1, "fmt".into()),
        (2, "flags".into()),
        (4, format!("nentry={}", hdr.nentry)),
        (4, format!("tail_off={}", hdr.tail_off)),
    ];
    let _ = write!(s, "      <TR>");
    for (span, lab) in &hdr_fields {
        let _ = write!(
            s,
            "<TD COLSPAN=\"{span}\" BORDER=\"0\"><FONT FACE=\"Helvetica\" POINT-SIZE=\"11\">{}</FONT></TD>",
            esc(lab)
        );
    }
    let _ = writeln!(s, "<TD COLSPAN=\"{}\" BORDER=\"0\"></TD></TR>", n - 12);

    // row 2: the bytes themselves, colored by role
    let _ = write!(s, "      <TR>");
    for (i, byte) in bytes.iter().enumerate() {
        let _ = write!(
            s,
            "<TD BGCOLOR=\"{f}\"><FONT FACE=\"Courier\" POINT-SIZE=\"12\">{byte:02X}</FONT></TD>",
            f = fills[i]
        );
    }
    let _ = writeln!(s, "</TR>");

    // row 3: byte offsets
    let _ = write!(s, "      <TR>");
    for i in 0..n {
        let _ = write!(
            s,
            "<TD BORDER=\"0\"><FONT FACE=\"Courier\" POINT-SIZE=\"9\">{i}</FONT></TD>"
        );
    }
    let _ = writeln!(s, "</TR>");

    // row 4: entry group labels (header columns stay blank)
    let _ = write!(s, "      <TR><TD COLSPAN=\"12\" BORDER=\"0\"></TD>");
    for (k, sp) in spans.iter().enumerate() {
        let role = if k % 2 == 0 { "field" } else { "value" };
        let _ = write!(
            s,
            "<TD COLSPAN=\"{span}\" BORDER=\"0\"><FONT FACE=\"Helvetica\" POINT-SIZE=\"11\">{lab}</FONT></TD>",
            span = sp.end - sp.start,
            lab = esc(&format!("{role} {}", sp.desc))
        );
    }
    let _ = writeln!(s, "</TR>");

    // row 5: tail_off marker under the last entry's first byte — an
    // in-table claim; a port self-edge routes straight through the cells.
    let last_start = spans.last().expect("nonempty").start;
    let _ = writeln!(
        s,
        "      <TR><TD COLSPAN=\"{last_start}\" BORDER=\"0\"></TD>\
<TD COLSPAN=\"{rest}\" BORDER=\"0\" ALIGN=\"LEFT\">\
<FONT FACE=\"Helvetica\" POINT-SIZE=\"10\">&#9650; tail_off</FONT></TD></TR>",
        rest = n - last_start
    );
    let _ = writeln!(s, "    </TABLE>>];");
    let _ = writeln!(s, "}}");
    s
}
