//! Byte-anatomy SVG for the ziplist hash golden block.
//!
//! Rebuilds the `tests/golden.rs::hash_golden_bytes` fixture through the
//! crate's own ops, then derives every drawn span by decoding the bytes
//! with the crate's own primitives (`BlockHeader::parse`, `Cursor`,
//! `decode`) — the figure cannot disagree with the codec without this
//! program aborting.
//!
//! The SVG is emitted directly: a byte grid is rigid (x-position IS the
//! byte offset), and a layout engine's routing freedom only fights that.
//! Emission is deterministic — integer geometry, fixed iteration order —
//! so freshness is provable on the one artifact readers actually see.
//! Regenerate:
//!   cargo run -p ziplist --example block_anatomy \
//!     > docs/diagrams/ziplist-block-anatomy.svg
//!
//! A future CI freshness check regenerates and diffs that SVG; there is
//! no separate render step whose toolchain version could perturb it.

use std::fmt::Write as _;
use ziplist::{decode, encode_into, encoded_len, BlockHeader, Cursor, EntryVal, HashMut, Type};

const CW: usize = 42; // byte cell width
const CH: usize = 34; // byte cell height
const X0: usize = 26; // grid origin x
const Y0: usize = 78; // grid origin y (leaves room for header brackets)
const H: usize = 236;

const HDR_FILL: &str = "#B3CDE3"; // header fields
const TAG_FILL: &str = "#FBB4AE"; // entry tag byte
const DATA_FILL: &str = "#CCEBC5"; // entry data bytes
const BL_FILL: &str = "#F6E3B4"; // backlen byte
const INK: &str = "#22303C"; // fixed ink: standalone <img> rendering
const BG: &str = "#FCFCFA"; // opaque ground for any host theme

/// tag + data length of an entry, from the public tier spec; verified in
/// `main` against `encoded_len` and a byte-identical re-encode.
fn tag_plus_data(val: &EntryVal) -> usize {
    match val {
        EntryVal::Uint(v) => match v {
            0..=250 => 1,
            251..=65535 => 3,
            65536..=16_777_215 => 4,
            16_777_216..=72_057_594_037_927_935 => 8,
            _ => 9,
        },
        EntryVal::Str(s) => {
            let mut varint = 1;
            let mut rest = s.len() >> 7;
            while rest > 0 {
                varint += 1;
                rest >>= 7;
            }
            1 + varint + s.len()
        }
    }
}

struct Span {
    start: usize,
    data_end: usize, // end of tag+data; backlen bytes run through `end`
    end: usize,
    desc: String,
}

fn main() {
    // The golden fixture, produced by the real ops.
    let mut buf = vec![0u8; 256];
    let mut h = HashMut::init(&mut buf).expect("init");
    h.hset(b"5", b"9").expect("hset 5");
    h.hset(b"z", b"ab").expect("hset z");
    let bytes: Vec<u8> = h.bytes().to_vec();

    // Derive spans with the crate's own decoder; abort on any mismatch.
    let hdr = BlockHeader::parse(&bytes).expect("header");
    assert_eq!(hdr.type_, Type::Hash, "fixture type drifted");
    let mut spans: Vec<Span> = Vec::new();
    let mut cur = Cursor::first(&bytes, &hdr);
    while let Some(c) = cur {
        let (val, total) = decode(&bytes, c.off).expect("entry decodes");
        let tpd = tag_plus_data(&val);
        assert_eq!(total, encoded_len(&val), "tier table drifted from codec");
        let backlen = total.checked_sub(tpd).expect("backlen underflow");
        assert!((1..=5).contains(&backlen), "backlen bytes out of range");
        // Re-encode and byte-compare: the drawn span is exactly the codec's.
        let mut re = vec![0u8; total];
        assert_eq!(encode_into(&val, &mut re), total);
        assert_eq!(re, bytes[c.off..c.off + total], "re-encode mismatch");
        let desc = match &val {
            EntryVal::Uint(v) => format!("Uint({v})"),
            EntryVal::Str(s) => format!("Str(\"{}\")", String::from_utf8_lossy(s)),
        };
        spans.push(Span {
            start: c.off,
            data_end: c.off + tpd,
            end: c.off + total,
            desc,
        });
        cur = c.next(&bytes);
    }
    assert_eq!(spans.len(), hdr.nentry as usize, "nentry != walked entries");
    assert_eq!(
        spans.last().expect("nonempty").start,
        hdr.tail_off as usize,
        "tail_off mismatch"
    );
    assert_eq!(
        spans.last().expect("nonempty").end,
        bytes.len(),
        "trailing bytes"
    );

    print!("{}", render_svg(&bytes, &hdr, &spans));
}

fn render_svg(bytes: &[u8], hdr: &BlockHeader, spans: &[Span]) -> String {
    let n = bytes.len();
    let w = X0 * 2 + CW * n;
    let esc = |t: &str| {
        t.replace('&', "&amp;")
            .replace('<', "&lt;")
            .replace('>', "&gt;")
    };
    let mut s = String::new();
    let _ = write!(
        s,
        "<!-- GENERATED by the ziplist block_anatomy example (cargo run); do not edit. \
         XML comments forbid double hyphens, so the full command lives in the example's header. -->\n\
         <svg viewBox=\"0 0 {w} {H}\" role=\"img\" aria-label=\"Byte-by-byte anatomy of a \
         {n}-byte ziplist hash block: 12-byte header (type, format, flags, nentry, tail_off) \
         followed by {ne} entries, each a tag byte, optional data bytes, and a backlen byte.\" \
         xmlns=\"http://www.w3.org/2000/svg\">",
        ne = hdr.nentry
    );
    let _ = write!(
        s,
        "<rect x=\"0\" y=\"0\" width=\"{w}\" height=\"{H}\" fill=\"{BG}\"/>\
         <style>text{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}}</style>"
    );

    // fills per byte
    let mut fills = vec![HDR_FILL; n];
    for sp in spans {
        fills[sp.start] = TAG_FILL;
        for f in fills.iter_mut().take(sp.data_end).skip(sp.start + 1) {
            *f = DATA_FILL;
        }
        for f in fills.iter_mut().take(sp.end).skip(sp.data_end) {
            *f = BL_FILL;
        }
    }
    for (i, byte) in bytes.iter().enumerate() {
        let x = X0 + i * CW;
        let _ = write!(
            s,
            "<rect x=\"{x}\" y=\"{Y0}\" width=\"{CW}\" height=\"{CH}\" fill=\"{f}\" \
             stroke=\"{INK}\" stroke-opacity=\"0.35\"/>\
             <text x=\"{tx}\" y=\"{ty}\" text-anchor=\"middle\" font-size=\"13\" \
             fill=\"{INK}\">{byte:02X}</text>",
            f = fills[i],
            tx = x + CW / 2,
            ty = Y0 + CH / 2 + 4,
        );
    }
    // offset ruler
    for i in 0..n {
        let _ = write!(
            s,
            "<text x=\"{x}\" y=\"{y}\" text-anchor=\"middle\" font-size=\"10\" fill=\"{INK}\" \
             opacity=\"0.55\">{i}</text>",
            x = X0 + i * CW + CW / 2,
            y = Y0 + CH + 16,
        );
    }

    let bracket =
        |s: &mut String, x1: usize, x2: usize, y: usize, label: &str, above: bool, mono: bool| {
            let (tick_y, ty) = if above {
                (y + 5, y - 6)
            } else {
                (y - 5, y + 16)
            };
            let fam = if mono {
                ""
            } else {
                " font-family=\"system-ui,sans-serif\""
            };
            let _ = write!(
                s,
                "<path d=\"M {x1} {tick_y} V {y} H {x2} V {tick_y}\" fill=\"none\" \
                 stroke=\"{INK}\" stroke-width=\"1.1\"/>\
                 <text x=\"{mx}\" y=\"{ty}\" text-anchor=\"middle\" font-size=\"12\"{fam} \
                 fill=\"{INK}\">{label}</text>",
                mx = (x1 + x2) / 2,
            );
        };

    // header field brackets, staggered to avoid label collisions
    let hdr_fields: [(usize, usize, String); 5] = [
        (0, 1, format!("type={:?}", hdr.type_)),
        (1, 2, "format".into()),
        (2, 4, "flags".into()),
        (4, 8, format!("nentry={}", hdr.nentry)),
        (8, 12, format!("tail_off={}", hdr.tail_off)),
    ];
    for (idx, (a, b, lab)) in hdr_fields.iter().enumerate() {
        let y = if idx % 2 == 0 { Y0 - 10 } else { Y0 - 38 };
        bracket(&mut s, X0 + a * CW + 2, X0 + b * CW - 2, y, lab, true, true);
    }

    // entry brackets below the ruler; roles alternate field/value in a hash
    let yb = Y0 + CH + 30;
    for (i, sp) in spans.iter().enumerate() {
        let role = if i % 2 == 0 { "field" } else { "value" };
        let label = format!("{role} {}", esc(&sp.desc));
        bracket(
            &mut s,
            X0 + sp.start * CW + 2,
            X0 + sp.end * CW - 2,
            yb,
            &label,
            false,
            true,
        );
    }

    // tail_off elbow: from the header field's bytes down and across to the
    // last entry's first byte — computed geometry, the reason this figure
    // is direct SVG rather than engine-routed.
    let hx = X0 + 8 * CW + CW / 2;
    let lx = X0 + spans.last().expect("nonempty").start * CW + CW / 2;
    let ya = Y0 + CH + 58;
    let _ = writeln!(
        s,
        "<path d=\"M {hx} {y1} V {y2} H {lx} V {y3}\" fill=\"none\" stroke=\"{INK}\" \
         stroke-width=\"1.2\" stroke-dasharray=\"4 3\" marker-end=\"url(#arr)\"/>\
         <text x=\"{mx}\" y=\"{ty}\" text-anchor=\"middle\" font-size=\"11\" \
         font-family=\"system-ui,sans-serif\" fill=\"{INK}\">tail_off points at the last \
         entry's first byte: O(1) tail access</text>\
         <defs><marker id=\"arr\" viewBox=\"0 0 8 8\" refX=\"7\" refY=\"4\" markerWidth=\"7\" \
         markerHeight=\"7\" orient=\"auto\"><path d=\"M0 0 L8 4 L0 8 z\" fill=\"{INK}\"/></marker>\
         </defs></svg>",
        y1 = Y0 + CH + 24,
        y2 = ya + 26,
        y3 = yb + 30,
        mx = (hx + lx) / 2,
        ty = ya + 40,
    );
    s
}
